baseURL = 'https://joungsik.github.io/'
languageCode = 'ko-kr'
title = 'JoungSik'
theme = "github-style"
googleAnalytics = "G-DL4SWDGV72"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "JoungSik"
  description = "Software Developer"
  github = "JoungSik"
  facebook = "100002406291053"
  instagram = "joungsik_kim"
  linkedin = "joungsik"
  email = "tjstlr2010@gmail.com"
  url = "https://joungsik.github.io"
  keywords = "blog"
  lastmod = true
  favicon = "/images/github.png"
  location = "Seoul"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
