baseURL = 'https://joungsik.github.io/'
languageCode = 'ko-kr'
title = 'Joungsik의 기술 블로그'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableRobotsTXT = true
titleCaseStyle = "Chicago"

[params]
  author = "JoungSik"
  description = "Software Developer"
  github = "JoungSik"
  facebook = "100002406291053"
  instagram = "main_jskim"
  linkedin = "joungsik"
  email = "tjstlr2010@gmail.com"
  url = "https://joungsik.github.io"
  keywords = "ruby, golang, ruby on rails, programming"
  rss = true
  lastmod = true
  userStatusEmoji = "🛠️"
  favicon = "/images/github-mark-white.png"
  avatar = "https://avatars.githubusercontent.com/u/6128807?v=4"
  headerIcon = "/images/github-mark-white.png"
  location = "Seoul"
  enableSearch = true
  enableGitalk = true
  custom_css = ["css/custom.css"]
  custom_js = ["js/application.js"]

[params.gitalk]
  clientID = "${GITALK_CLIENT_ID}"
  clientSecret = "${GITALK_CLIENT_SECRET}"
  repo = "joungsik.github.io"
  owner = "JoungSik"
  admin = "JoungSik"
  id = "location.pathname"
  labels = "gitalk"
  perPage = 15
  pagerDirection = "last"
  createIssueManually = true
  distractionFreeMode = false

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"